export enum UserRole {
  ADMIN = 'ADMIN',
  VP_SALES = 'VP_SALES',
  SALES_MANAGER = 'SALES_MANAGER',
  SALES = 'SALES',
  REGIONAL_DIRECTOR_OPS = 'REGIONAL_DIRECTOR_OPS',
  DISTRICT_SERVICE_MANAGER = 'DISTRICT_SERVICE_MANAGER',
  CLIENT = 'CLIENT',
  COLLECTOR = 'COLLECTOR',
}

export enum PropertyStatus {
  DRAFT = 'DRAFT',
  PENDING_OPS = 'PENDING_OPS',
  PENDING_DISTRICT_MANAGER = 'PENDING_DISTRICT_MANAGER',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum StartType {
  NEW_CONSTRUCTION = 'NEW_CONSTRUCTION',
  PHASE_IN = 'PHASE_IN',
  VENDOR_CHANGE = 'VENDOR_CHANGE',
  RENEWAL = 'RENEWAL',
}

export enum BuildingType {
  HIGH_RISE = 'HIGH_RISE',
  MID_RISE = 'MID_RISE',
  GARDEN_STYLE = 'GARDEN_STYLE',
}

export enum AccessType {
  NONE = 'NONE',
  KEY_FOB = 'KEY_FOB',
  DIGITAL_KEY = 'DIGITAL_KEY',
  KEY = 'KEY',
}

export enum DisposalType {
  COMPACTOR = 'COMPACTOR',
  DUMPSTER = 'DUMPSTER',
}

export enum CollectionType {
  POV_SATCHEL = 'POV_SATCHEL',
  HAND_CART = 'HAND_CART',
}

export enum StartTime {
  AM = 'AM',
  SEVEN_PM = '7PM',
  EIGHT_PM = '8PM',
}

export enum TicketStatus {
  OPEN = 'OPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
}

export enum TicketPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}

export enum ViolationType {
  ISSUED_CONTAINER_NOT_USED = 'ISSUED_CONTAINER_NOT_USED',
  TRASH_ON_FLOOR = 'TRASH_ON_FLOOR',
  BAG_RIPPING_TEARING = 'BAG_RIPPING_TEARING',
  EXCESSIVE_WASTE = 'EXCESSIVE_WASTE',
  TRASH_BAG_NOT_TIED = 'TRASH_BAG_NOT_TIED',
  LARGE_ITEMS = 'LARGE_ITEMS',
  BOXES_NOT_BROKEN_DOWN = 'BOXES_NOT_BROKEN_DOWN',
  LOOSE_TRASH_IN_CONTAINER = 'LOOSE_TRASH_IN_CONTAINER',
  PET_WASTE_NOT_DOUBLE_BAGGED = 'PET_WASTE_NOT_DOUBLE_BAGGED',
  HAZARDOUS_MATERIALS = 'HAZARDOUS_MATERIALS',
  SHARP_OBJECTS = 'SHARP_OBJECTS',
}

export enum ViolationStatus {
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  SENT = 'SENT',
}

export enum RouteStatus {
  NOT_STARTED = 'NOT_STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  MISSED = 'MISSED',
}

export enum InvoiceStatus {
  DRAFT = 'DRAFT',
  SENT = 'SENT',
  PAID = 'PAID',
  OVERDUE = 'OVERDUE',
  CANCELLED = 'CANCELLED',
}

export enum PaymentMethod {
  CREDIT_CARD = 'CREDIT_CARD',
  CHECK = 'CHECK',
  ACH = 'ACH',
}

export enum CommunicationType {
  EMAIL = 'EMAIL',
  SMS = 'SMS',
  CALL = 'CALL',
}
